### ISSUE TITLE
I couldn't get it to install on UE 5.0.3

### ISSUE THREAD

**Issue by DrSharky** [thomasfn/HL2UE4AssetImporter#10]
I'm totally willing to learn what I'm doing wrong, but I followed the installation steps exactly, and it fails to build the plugin. I'm using version 5.0.3.

**Comment by thomasfn** [comment]
Are you able to provide any sort of error messages or log output? If you can't even get the editor to load due to it failing to compile, you may need to use the unreal build tool utility to generate VS project files, load the project in VS and compile it from there, which will give you more useful errors. The good news is you won't need to build the whole engine from scratch that route, only the plugin and project local files.

**Comment by DrSharky** [comment]
Thanks, I will try building that way. I am fairly new to Unreal so I didn't know I had options like that.

**Comment by DrSharky** [comment]
So after reading your comment and doing some research, I realize that my problem was that I tried to build the plugin with a Blueprint project instead of a C++ project. I followed the install instructions as closely as I could, but I suppose the detail of using a C++ project base was lost on me. It works fine in UE 5.0.3 if I make the base project C++, which makes a lot more sense. Thanks for your patience, like I said, I'm new to Unreal Engine.
